apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}-main
        image: {{ .Values.app.image}}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: {{ .Values.app.name }}-index
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "250Mi"
            cpu: "200m"
          limits:
            memory: "250Mi"
            cpu: "200m"
      volumes:
      - name: {{ .Values.app.name }}-index
        configMap:
          name: {{ .Values.app.name }}-index-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-index-config
  namespace: {{ .Values.app.namespace }}
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <!-- Prevent caching of the HTML document -->
        <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
        <meta http-equiv="Pragma" content="no-cache">
        <meta http-equiv="Expires" content="0">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Landing Page</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <style>
            body {
                background-color: #007bff; /* Blue background */
                height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
            }
            .box {
                background: white;
                padding: 40px;
                border-radius: 10px;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div class="box">
            <h1>Hello, new version {{.Chart.Version}}</h1>
        </div>
    </body>
    </html>

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  namespace: {{ .Values.app.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.name }}
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
